language: c
compiler:
  - gcc
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "fKWhlBJ4puwj6toOuQe/TaCF4kks6XzIYMl92QzT8Xq9DF+2idJCnmWnol9k2cnPQ+34Y/WCbw+mijj7AeerTRXBbClsoPhneeLJTgcycrXYPzeqfKQArGRAH33F8ItkO9JQWrs1an1Zrk1ORGxb8rM9CGv9R+hyBUqQBNru4faJk/hLZe7oh+CvZU4Th6HxFT3s3LHBcoIdyAuhZSanV0zzQ3mgPZdI3OVtvadpPxc1csQrVFmYkVhAAE3JH1o+gEtPXRNxIyUIZaxuFbVMZ2Qsm89diAXtfywn+RQKLNwtlQnXOj+gG0F1U3KdaoTwRx6KCrY3nQPy34ZgN+riLb2g+yt6f5MsgAVM8mpL+lyFXvlkwSXvYzn0TR2KO8SMqxSpalU4LUGTMZA5MpnDOVfWQIZ79kuA3DvrMselCBaRP5+JC1R2/6tyyalzVzTO0JOE92ht6eJQY7SeJGT94cYffwUfJQ5ENtPs6OzbM87r/AOdSmMRgcfDsPZDiTwtEfW9sBTGEzZdxq7inJzjEDB9exLQBzX4S/P1TxhC22i75/thqIJ2sV40TSGrn8LdMqw0CGgijnLWR51apsE0wg4FtQsFzOb0cb0Ia8cYk/onMenpFAwEYC/ZE1NHeEXYz5rc7da/Zj1iz4Q+Cmj+KVI2j47NQjOIamso+XcWP9g="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Reaves1234/WinSCP"
      description: "<Your project description here>"
    notification_email: bryantdreaves@gmail.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command: "<Your build command here>"
    branch_pattern: coverity_scan
